name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Authenticate into Google Cloud Platform
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use Google Cloud Platform
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker --quiet"

      - name: Install docker-credential-gcr
        uses: actions/gcloud/cli@master
        with:
          args: "components install docker-credential-gcr"

      - run: sudo ln -s /opt/google-cloud-sdk/bin/docker-credential-gcr /usr/bin/docker-credential-gcr

      - run: docker-credential-gcr config --token-source="gcloud"

      - run: ./mvnw compile test com.google.cloud.tools:jib-maven-plugin:1.8.0:build -Dimage=gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}

      - name: Deploy on cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "gcloud run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed"
